# Generated by Django 6.0.2 on 2026-04-01 00:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermobile',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
