# Generated by Django 6.0.3 on 2026-05-18 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_auth_kit', '0002_alter_useremail_id_alter_usermobile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermobile',
            name='id',
            field=models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
